kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: "{{ default "filemanager" .Values.deployment.name }}-data"
  annotations:
    volume.beta.kubernetes.io/storage-class: efs-development
spec:
  storageClassName: efs-development
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
