kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
  name: "{{ default "filemanager" .Values.serviceName }}"
  labels:
    subsystem: "{{ .Values.labels.subsystem }}"
    container: "{{ default "filemanager" .Values.deploymentName }}"
    service-group: backend
    log-style: uwsgi
    env: "{{ .Values.namespace }}"
  namespace: "{{ .Values.namespace }}"
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8000
  selector:
    subsystem: "{{ .Values.labels.subsystem }}"
    container: "{{ default "filemanager" .Values.deploymentName }}"
