language: python
sudo: required
env:
  MIN_PYLINT_SCORE: 8
  LOGLEVEL: 40
  SQLALCHEMY_DATABASE_URI: "sqlite://"
  PIPENV_IGNORE_VIRTUALENVS: 1
os:
  - linux
python:
  - "3.6"
script:
  - pip install pipenv
  - pipenv sync --dev
  - pipenv run nose2 --with-coverage --coverage-report=term-missing
after_success:
  - coveralls
  - "./tests/lint.sh filemanager"
  - "./tests/style.sh filemanager"
  - "./tests/type-check.sh filemanager"

deploy:
- provider: script
  script:
    ./deploy/make_and_push_image.sh filemanager
  on:
    all_branches: true
- provider: script
  script:
    ./deploy/make_and_push_image.sh filemanager &&
    ./deploy/install_helm.sh &&
    ./deploy/publish_helm_chart.sh &&
    ./deploy/deploy.sh filemanager development
  on:
    tags: true
