namespace: development
deployment:
  name: filemanager
service:
  name: filemanager
image:
  tag: "0.3"
labels:
  subsystem: submission

replicas: 1

vault:
  host: changeme
  port: changeme
  role: filemanager

database:
  host: changeme

loglevel: 10
