namespace: development
deployment:
  name: filemanager
service:
  name: filemanager
image:
  tag: 0.0.4
labels:
  subsystem: submission
secrets:
  jwt:
    name: jwt-secret-name
    key: jwt-secret-key
replicas: 1

database:
  secret:
    name: "changeme"
    key: "changeme"

loglevel: 10
